queries = [
    # Textual Queries
    "What are the dimensions of a badminton court?",
    "Describe the serving rules in doubles badminton.",
    "How is a judo match scored?",
    "What are the main objectives of playing basketball?",
    "Explain the fouling rules in the olympic sport of basketball.",
    "What are the stages in a gymnastics routine?",
    "How does scoring work in Olympic boxing?",
    "Describe the responsibilities of a boxing referee.",
    "What are the rules for serving in tennis?",
    "Explain the rules for a three-point shot in basketball.",
    "What is considered a foul in wrestling?",
    "Describe the point system in weightlifting.",
    "What are the different kicks in taekwondo?",
    "Explain the scoring rules in taekwondo.",
    "How does a freestyle wrestling match begin?",
    "What is the purpose of the D-score in gymnastics?",
    "Describe the rules of passive play in handball.",
    "What happens when there is a tie in boxing?",
    "Explain the structure of a weightlifting competition.",
    "Describe the equipment required for table tennis.",
    "How is fair play ensured in gymnastics?",
    "What are the moves allowed in judo?",
    "Describe the rules for backcourt violations in basketball.",
    "What are the rules for penalties in handball?",
    "Explain the qualification process for gymnastics finals.",
    "What is a 'technical pin' in wrestling?",
    "Describe the elements of a breaking routine.",
    "What is the main objective in freestyle wrestling?",
    "How are battles structured in breakdancing?",
    "Describe the process of scoring in a judo competition.",
    "What is the purpose of the Code of Points in gymnastics?",
    "Explain how points are deducted in gymnastics.",
    "What are the scoring criteria in fencing?",
    "Describe the Olympic lifting techniques.",
    "Explain the rules of fair play in badminton.",
    "Describe the process of scoring in table tennis.",
    "How does a team qualify for gymnastics finals?",
    "Describe the structure of an Olympic boxing match.",
    "Explain how penalties are issued in soccer.",
    "What are some common techniques in breaking?",
    "Describe the role of a coach in gymnastics.",
    "What is the value of a double hit in badminton?",
    "How is a gold medal awarded in Olympic weightlifting?",
    "What is the duration of each round in taekwondo?",
    "How are penalties handled in handball?",
    "Explain the rules for scoring in basketball.",
    "Describe the purpose of the federation for fencing.",
    "What is required for a gymnast to earn bonus points?",
    "Explain the concept of 'passive play' in handball.",
    "What is the judging process in Olympic breaking?",

    # Analytical Queries
    "When and where did Dhyan Chand die",
    "Name all the female athletes who are alive and played for Papua New Guinea",
    "Which country has the highest number of gold medals?",
    "How many silver medals has Mark Spitz won",
    "How many female athletes participated in the 2016 Olympics?",
    "Find athletes from Pakistan who participated in more than one Olympic edition",
    "How many times has the United States hosted the Olympics?",
    "How many countries participated in the 2012 Olympics?",
    "Which athlete has won the most medals in Olympic history?",
    "How many gold medals were won in the 2004 Olympics?",
    "Find athletes who won medals in the 2020 Olympics in Men's Surfing",
    "Find athletes who won the highest total medals but never finished 1st in any event",
    "How many athletes won medals in more than one event?",
    "How many Olympic games has India participated in?",
    "How many medals did female athletes from Canada win in 2016 Olympics?",
    "What is the total count of medals won by athletes from Japan?",
    "List athletes who competed in basketball for team Australia",
    "What is the average number of medals won by each country?",
    "How many athletes participated in athletics as a sport in the 2008 Olympics?",
    "What was the medal count for the Russian athletes in 2012?",
    "Which athlete has won the most gold medals in a single edition of the Olympics?",
    "How many athletes were affiliated with the NOC 'AUS' during 2016 Olympics?",
    "What is the total medal count for China?",
    "ist athletes from Pakistan who participated but did not win any medals.",
    "How many athletes from France have competed in swimming events?",
    "How many athletes were under the age of 18 during the 2016 Olympics?",
    "What is the total number of medals won by male athletes from Australia in Men's Boxing?",
    "How many countries have won at least one medal in weightlifting?",
    "Who won the gold medal in Men's Wrestling in 2004 Summer Olympics?",
    "What is the total number of medals won in Hockey by India?",
    "Which country hosted the 2020 Olympics?",
    "How many athletes represented China in the 2012 Olympics?",
    "Which country had the largest number of participants in the 1996 Olympics?",
    "How many Olympic medals have been won by athletes over the age of 50?",
    "How many countries have competed in every Olympic Games?",
    "How many Indian athletes have bagged gold medals?",
    "How many athletes from Nigeria won medals in athletics?",
    "Name all the atheletes from Canada who were died before 1st January, 1990",
    "Is Carl Lewis alive?",
    "How many times did athletes from Brazil win medals in judo?",
    "Which country won Silver medal in Womens Hockey at 2020 Summer Olympics",
    "How many athletes from Russia participated in the 2018 Summer Olympics?",
    "What was the average age of medal-winning athletes from India?",
    "How many athletes competed in the 2000 Olympics in Sydney?",
    "What is the average medal count per athlete for athletes born after 1990?",
    "How many male athletes from Canada participated in hockey events?",
    "What is the ratio of male to female athletes in the 2016 Olympics?",
    "How many total medals were awarded in the 2016 Olympics?",
    "Name the members of the mens hockey team who won Gold medal in 1956 Summer Olympics",
    "How many times did athletes from Japan participate in karate events?",
    "What were the position of India athletes in Badminton sport in the last 2 editions of Olympics",

    # Web-based Queries
    "Who won the most gold medals in the 2024 Olympics?",
    "What new sports were introduced in the 2024 Olympics?",
    "Who was the flag bearer for the United States in the opening ceremony of the 2024 Olympics?",
    "How many records were broken during the 2024 Olympics?",
    "What was the overall medal count for France in the 2024 Olympics?",
    "How many athletes participated in the 2024 Olympics?",
    "What was the medal distribution between male and female athletes in the 2024 Olympics?",
    "Who was the youngest medalist at the 2024 Olympics?",
    "What were the main controversies or highlights of the 2024 Olympics?",
    "Who was the oldest athlete competing in the 2024 Olympics?",
    "Which country had the largest contingent of athletes in the 2024 Olympics?",
    "Which city will host the next Summer Olympics after 2024?",
    "Which Olympic events were canceled or modified in 2024, if any?",
    "What were the top social media trends related to the 2024 Olympics?",
    "Who won the gold medal in men’s basketball in the 2024 Olympics?",
    "How did Team India perform in the 2028 Olympics?",
    "What was the total budget for hosting the 2024 Olympics?",
    "Which athletes won medals for the first time in the 2024 Olympics?",
    "Who performed at the 2024 Olympics closing ceremony?",
    "How many countries won at least one medal in the 2024 Olympics?"
]
